### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by lexicona1** [joelnir/SplitNotes#15]
I recently reset my OS and have been trying to restore .dll's and whatnot.  I restored one that it said it needed (i don't remember which, sorry), but now it's just saying it can't open.  I've tried installing python and trying to see what the issues are.  This is what i get:

Exception in Tkinter callback
Traceback (most recent call last):
  File "F:\Program\python3.4\lib\tkinter\__init__.py", line 1482, in __call__
  File "F:\Program\python3.4\lib\tkinter\__init__.py", line 534, in callit
  File "main_window.py", line 57, in update
  File "C:\Users\Joel\Desktop\Dev SplitNotesa\ls_connection.py", line 88, in get_split_index
ValueError: invalid literal for int() with base 10: ''
Exception in Tkinter callback
Traceback (most recent call last):
  File "F:\Program\python3.4\lib\tkinter\__init__.py", line 1482, in __call__
  File "F:\Program\python3.4\lib\tkinter\__init__.py", line 534, in callit
  File "main_window.py", line 57, in update
  File "C:\Users\Joel\Desktop\Dev SplitNotesa\ls_connection.py", line 88, in get_split_index
ValueError: invalid literal for int() with base 10: '3:36:40.81\r\n'
Exception in Tkinter callback
Traceback (most recent call last):
  File "F:\Program\python3.4\lib\tkinter\__init__.py", line 1482, in __call__
  File "F:\Program\python3.4\lib\tkinter\__init__.py", line 534, in callit
  File "main_window.py", line 57, in update
  File "C:\Users\Joel\Desktop\Dev SplitNotesa\ls_connection.py", line 88, in get_split_index
ValueError: invalid literal for int() with base 10: ''
Exception in Tkinter callback
Traceback (most recent call last):
  File "F:\Program\python3.4\lib\tkinter\__init__.py", line 1482, in __call__
  File "F:\Program\python3.4\lib\tkinter\__init__.py", line 534, in callit
  File "main_window.py", line 57, in update
  File "C:\Users\Joel\Desktop\Dev SplitNotesa\ls_connection.py", line 88, in get_split_index
ValueError: invalid literal for int() with base 10: '0.00\r\n'
Exception in Tkinter callback
Traceback (most recent call last):
  File "F:\Program\python3.4\lib\tkinter\__init__.py", line 1482, in __call__
  File "F:\Program\python3.4\lib\tkinter\__init__.py", line 534, in callit
  File "main_window.py", line 57, in update
  File "C:\Users\Joel\Desktop\Dev SplitNotesa\ls_connection.py", line 88, in get_split_index
ValueError: invalid literal for int() with base 10: ''
Exception in Tkinter callback
Traceback (most recent call last):
  File "F:\Program\python3.4\lib\tkinter\__init__.py", line 1482, in __call__
  File "F:\Program\python3.4\lib\tkinter\__init__.py", line 534, in callit
  File "main_window.py", line 57, in update
  File "C:\Users\Joel\Desktop\Dev SplitNotesa\ls_connection.py", line 88, in get_split_index
ValueError: invalid literal for int() with base 10: ''
Exception in Tkinter callback
Traceback (most recent call last):
  File "F:\Program\python3.4\lib\tkinter\__init__.py", line 1482, in __call__
  File "F:\Program\python3.4\lib\tkinter\__init__.py", line 534, in callit
  File "main_window.py", line 57, in update
  File "C:\Users\Joel\Desktop\Dev SplitNotesa\ls_connection.py", line 88, in get_split_index
ValueError: invalid literal for int() with base 10: '0.00\r\n-1\r\n'

Let me know if you know anything.  Thank you in advance

**Comment by lexicona1** [comment]
Update, windows is saying it's incompatible.  i'm at a loss. 
![image](https://user-images.githubusercontent.com/43022119/45133354-86f91580-b149-11e8-853e-c0d704c37109.png)

**Comment by joeloskarsson** [comment]
Hello

It's been a while since I touched this project, but I'll try to help you from what I remember. The trace seems to point towards there being some issue with data received from the livesplit server. Do you have livesplit running when starting splitnotes? In what order do you start splitnotes, livesplit and livesplit server? Does it crash on startup no matter the order? Do you have anything else running on the selected port? If you haven't managed to get to the settings for server port it defaults to 16834.

I haven't stayed up to date with livesplit development, so I hope there hasn't been changes to the server component. I'll investigate this further.

No idea what the windows "incompatible program" thing means. That's quite strange.

**Comment by lexicona1** [comment]
Hey!  So i guess for more background info, this issue was being recieved (pictured below) whenever i try to open the application regardless.

![image](https://user-images.githubusercontent.com/43022119/45140455-b159cb80-b167-11e8-9c85-b9ed5597f46d.png)

Also, i think the information i sent you was outdated and old information that i worked past.  As of right now, the only lead we have is the picture i sent with this message.

**Comment by joeloskarsson** [comment]
So it does seem that the issue indeed is some missing .dll files that you must have lost when resetting your OS. Googling the error message (0xc000007b) shows some threads from people with similar issues and some proposed fixes. Have you tried running it as admin?

Have you moved the .exe after extracting the .zip? There are .dll:s in the folder that are crucial for the program.

**Comment by lexicona1** [comment]
I have attempted most solutions online, including running it in admin, and yes i'm running it in the same folder i extracted everything into

**Comment by lexicona1** [comment]
update!  i had some friends who were able to pinpoint the issue, it was a discrepancy between 32 and 64 bit for a .dll

**Comment by joeloskarsson** [comment]
Nice, so does everything work now after fixing the .dll?

If you don't mind it would be great if you could write the exact name of the .dll and briefly how you fixed it. Then if someone has the same issue in the future they could find this thread. It would be very much appreciated. :)

**Comment by lexicona1** [comment]
oh yeah of course!  Everything works now, and here was the solution.  I only had the 64-bit version of the msvcr100.dll file, and your application uses the 32 bit version, so what i did was i still had the 32 bit version, identifiable by the 755 MB size instead of the 64 bit's 806 MB, and moved it to the folder with main_window.exe
